### ISSUE TITLE
due to the fact you're using implementations directly, method is missing in interface...

### ISSUE THREAD

**Issue by DGrudzynskyi** [AlikTheCreator/VoteSystemFI#2]
https://github.com/AlikTheCreator/VoteSystemFI/blob/0741bd852b74f30f1365d665b2c270977e1f9007/VoteSystem.Console/Program.cs#L118

And generally speaking interface become outdated as it is no more reflecting "what's needed" by application.
I am speaking about method CheckAllPolicy

**Comment by AlikTheCreator** [comment]
fixed already
