### ISSUE TITLE
Repository does not fetch "whole" aggregate

### ISSUE THREAD

**Issue by DGrudzynskyi** [AlikTheCreator/VoteSystemFI#3]
https://github.com/AlikTheCreator/VoteSystemFI/blob/0741bd852b74f30f1365d665b2c270977e1f9007/VoteSystem.Data/Repositories/IPollRepository.cs#L12

an "aggregate" shall always be materialized 'as a whole'. E.g. with all it's references.

I see that you're not initializing choices for poll in method GetPoll - and it cause multiple different methods: GetChoices, GetChoices by name e.t.c.

Instead - make sure that whatever is returned from the repository is "always fully initialized". Repositories shall never return half-way-fetched aggregates.

**Comment by AlikTheCreator** [comment]
we have atomary action as adding choice to poll in fact poll can be created without choices

**Comment by DGrudzynskyi** [comment]
> we have atomary action as adding choice to poll in fact poll can be created without choices

Absolutely, but you still have to initialize all entities of aggregate. Even if there are actually "no" such entities present
